Stop active support of cross-compilation for Windows
sociomantic/libdrizzle-redux pull request #195
Opened 2017-07-06 14:31 UTC by andreas-bok-sociomantic

Updated documentation after removing active support
for MinGW cross-compilation

2017-07-06 16:01 UTC, mathias-lang-sociomantic commented on RELEASE_NOTES.md
> +As mentioned in the release notes for [v5.5.3](https://github.com/sociomantic-tsunami/libdrizzle-redux/releases/tag/v5.5.3)_ the MinGW is broken.
the MinGW *build* is broken

2017-07-06 16:03 UTC, mathias-lang-sociomantic requested changes
Just a typo, oLGTM

2017-07-14 09:35 UTC, andreas-bok-sociomantic commented
ping @mathias-lang-sociomantic

2017-07-14 13:31 UTC, mathias-lang-sociomantic commented on RELEASE_NOTES.md
> +Thus, should any contributers wish to add MinGW support again, they are more
`contributors`

2017-07-14 13:32 UTC, andreas-bok-sociomantic commented on RELEASE_NOTES.md
> +Thus, should any contributers wish to add MinGW support again, they are more
Damn it

2017-07-14 13:45 UTC, andreas-bok-sociomantic commented
Fixed typo

2017-07-14 14:04 UTC, mathias-lang-sociomantic approved these changes

2017-07-14 14:04 UTC, merged