Add the ability to actually use OpenSSL
sociomantic/libdrizzle-redux pull request #78
Opened 2016-11-25 16:52 UTC by mathias-lang-sociomantic

Before, it was not possible to enable OpenSSL support in libdrizzle-redux since the configure script didn't support enabling it (though it required openssl to be installed).

Expected results (and performed tests, on linux):
- `./configure`
- `./configure --enable-ssl[=yes]`
- `./configure --disable-ssl` (or `./configure --enable-ssl=no`)

Followed by `ldd libdrizzle/.libs/libdrizzle-redux.so`

In the first and second case, I get:
```
	linux-vdso.so.1 =>  (0x00007fffc69e3000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f235b7f1000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f235b592000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f235b1b6000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f235aea4000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f235ab9e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f235a7d9000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f235a5c2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f235a3be000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f235bc25000)
```

Before this P.R., and with the third version, I get:
```
	linux-vdso.so.1 =>  (0x00007ffecefbd000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f51f80c1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f51f7daf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f51f7aa9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f51f76e4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f51f74cd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f51f84f4000)
```

2016-11-25 17:03 UTC, andreas-bok-sociomantic requested changes

2016-11-25 17:03 UTC, andreas-bok-sociomantic commented on configure.ac
> +# SSL support, for encrypted connections
It should go into a separate macro and be included from the m4 dir.

2016-11-25 17:03 UTC, andreas-bok-sociomantic commented on configure.ac
> +# SSL support, for encrypted connections
It seems out of line with the format of the `configure.ac` to have it inline

2016-11-25 17:05 UTC, andreas-bok-sociomantic commented
Checked the build failure on travis 

```sh
libdrizzle/conn.cc:1261:80: error: implicit conversion loses integer precision:
      'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
  ...SSL_read(con->ssl, (char*)con->buffer_ptr + con->buffer_size, available_buffer);
     ~~~~~~~~                                                      ^~~~~~~~~~~~~~~~
libdrizzle/conn.cc:1384:61: error: implicit conversion loses integer precision:
      'size_t' (aka 'unsigned long') to 'int' [-Werror,-Wshorten-64-to-32]
      write_size= SSL_write(con->ssl, con->buffer_ptr, con->buffer_size);
```
I have a docker image set up for cross compilation of the project. So I will fix that error

2016-11-25 17:10 UTC, andreas-bok-sociomantic commented
Maybe rephrase second ci msg to
 > OpenSSL: Fix broken enable/disable option in configure script

2016-11-25 17:18 UTC, mathias-lang-sociomantic commented
Appeased the Travis gods. Gonna split the rest out on Monday :)

2016-11-28 11:44 UTC, mathias-lang-sociomantic commented
Updated

2016-11-28 13:18 UTC, andreas-bok-sociomantic approved these changes

2016-11-28 13:32 UTC, andreas-bok-sociomantic commented
LGTM

2016-11-30 10:24 UTC, merged